services:

  flipkart-api:
    build: .
    mem_limit: 128m
    ports:
      - "8003:8000"
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    name: rustfs_default
    external: true
